bracketSpacing: true
singleQuote: false
trailingComma: "none"
semi: false
tabWidth: 2
printWidth: 80
proseWrap: "always"

plugins:
  - prettier-plugin-svelte

overrides:
  - files: "*.svelte"
    options:
      parser: svelte
