name: Deploy Documentation

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - "docs/**"
      - "mkdocs.yml"

permissions:
  id-token: write
  pages: write
  contents: write

jobs:
  build-docs:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Push Build Artifact
        run: |
          mkdocs gh-deploy --force --message "cd: deploy docs from {sha}"

  publish-docs:
    environment: Docs
    name: Publish Documentation
    runs-on: ubuntu-latest
    needs: build-docs
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "."

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
